# Documentation: http://docs.travis-ci.com/user/build-configuration/
# Documentation: http://docs.travis-ci.com/user/languages/ruby/

language: ruby
rvm:
  - 2.1.2

# Environment Variables
env:
  global:
    - RAILS_ENV=test
    - TZ=America/New_York # Set the system Time Zone to be EST
    - DISPLAY=:99.0 # Display port
    -
      # Code Climate Test Coverage Integration
      secure: FW8A6JKXmOcOBIYIJ9OKui+Zh4S2o/o1rHYdIEEddiA/eGX8YK5jC80zS9aNQF35bQgSwl8BMND3ot0cD2uIkPN7EokTCiM+BSAmS/ef7v8j36f0CzxOJj/N99BfXukxS0ohi6qMCu/TchXS2vc2gZFIsyq3k7c1ui0IiMgkRLk=

# Dependencies
before_install:
  - convert -version # Check ImageMagick version
  - sudo apt-get update
  - sudo apt-get install -y qt-sdk
  - sh -e /etc/init.d/xvfb start # Start xvfb virtual display used by Capybara
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # Don't install docs

# Installation
bundler_args: --without development

# Caching the gems and dependencies, not available for now
cache:
  - bundler
  - apt

# Run before the script
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

# Jobs to test on the script
script:
  - bundle exec rake spec

# Notifications
notifications:
  email: false
  slack:
    secure: cgNX+p8In037Pf6Dylc0JU9NkqBehxvfAnq2hsdDJS3C/J+JNF1O4u6obCBsuhXIOYCbqB02XZ/Mvu+iw/toVlMgrCyMyW+OBbGEMBUngrrjMTuOtmhizyH/1xlG05Eg70+DbdEHzu8pdtcs6sS+Lt64ME3GLyZoym76yAp8o44=
